# Generated by Django 6.0.2 on 2026-02-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('summary', models.TextField()),
                ('skills', models.TextField(help_text='Comma separated')),
                ('experience', models.TextField()),
                ('projects', models.TextField()),
                ('education', models.TextField()),
                ('uploaded_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('generated_pdf', models.FileField(blank=True, upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
